### ISSUE TITLE
Controllerテストの失敗パターンを記述する

### ISSUE THREAD

**Issue by yuki-b4** [ssagara00/rails_app#12]
## 内容
[posts_spec.rb](https://github.com/ssagara00/rails_app/blob/main/spec/requests/posts_spec.rb)
成功パターンは記載されていますが、失敗したパターンが存在する場合も[posts_controller.rb](https://github.com/ssagara00/rails_app/blob/main/app/controllers/posts_controller.rb)では存在しているようなので、網羅性を高めるために記述を行う

## 補足
優先順位でいくと現状は[このスレッド](https://saito-mentee.slack.com/archives/D04D7DS8PDH/p1675427102944699?thread_ts=1675407037.723629&cid=D04D7DS8PDH)で指摘したことの方が優先度は高い。
理由は、データを操作できないことやデータが正しく操作できているかを保証する方が信頼できる。つまりユーザーの満足度に直結するため。

**Comment by 5hun-s** [comment]
modelのバリデーションの実装に合わせて行う。

**Comment by 5hun-s** [comment]
修正したため、終了。
